/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Gestion;

import Vista.Producto.listProduct;
import static Vista.Producto.listProduct.pnlLPr;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;

/**
 *
 * @author issacpuga
 */
public class panelGestion extends javax.swing.JPanel {

    public panelGestion() {
        initComponents();
        this.setBackground(Color.white);
        
        this.ventaEst();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEstadis = new javax.swing.JButton();
        pEstad = new javax.swing.JPanel();

        btnEstadis.setText("Ventas Generales");
        btnEstadis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEstadLayout = new javax.swing.GroupLayout(pEstad);
        pEstad.setLayout(pEstadLayout);
        pEstadLayout.setHorizontalGroup(
            pEstadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pEstadLayout.setVerticalGroup(
            pEstadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEstadis)
                .addContainerGap(1149, Short.MAX_VALUE))
            .addComponent(pEstad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEstadis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pEstad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstadisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisActionPerformed
        this.ventaEst();
    }//GEN-LAST:event_btnEstadisActionPerformed

    public void ventaEst(){
        VentGene mE = new VentGene();
        mE.setSize(1288, 535);
        mE.setLocation(0, 0);
        pEstad.removeAll();
        pEstad.add(mE, BorderLayout.CENTER);
        pEstad.revalidate();
        pEstad.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnEstadis;
    javax.swing.JPanel pEstad;
    // End of variables declaration//GEN-END:variables
}
