/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Gestion;

import Controlador.Gestion;
import Controlador.Productos;
import Controlador.Ventas;
import Modelo.sqlGestion;
import Modelo.sqlProductos;
import Modelo.sqlVentas;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author issacpuga
 */
public class VentGene extends javax.swing.JPanel {
    ResultSet rs;
    JTable TEstVen;
    public int idV;
    DefaultTableModel dtm = new DefaultTableModel();
    public VentGene() {
        initComponents();
        this.setBackground(Color.white);
//        this.lblDinTot.setText("5000");
//        this.lblTotVent.setText("50");
        
        Calendar c2 = new GregorianCalendar();
        jFecha.setCalendar(c2);
        
        tbl();
//        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
//        String date = dcn.format(jFecha.getDate() );
       
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenGen = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotVent = new javax.swing.JLabel();
        lblDinTot = new javax.swing.JLabel();
        btnMV = new javax.swing.JButton();
        btnEV = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        jFecha.setBorder(new javax.swing.border.MatteBorder(null));
        jFecha.setDateFormatString("yyyy-MM-dd");
        jFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jFechaMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel1.setText("Dia:");

        tblVenGen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVenGen);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Ventas Realizadas:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Total:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 23)); // NOI18N
        jLabel4.setText("$");

        lblTotVent.setFont(new java.awt.Font("Helvetica Neue", 1, 23)); // NOI18N

        lblDinTot.setFont(new java.awt.Font("Helvetica Neue", 1, 23)); // NOI18N

        btnMV.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMV.setText("Mostrar Venta");
        btnMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMVActionPerformed(evt);
            }
        });

        btnEV.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnEV.setText("Eliminar Venta");
        btnEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEVActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEV))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotVent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDinTot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnMV)
                                .addComponent(btnEV)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblTotVent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lblDinTot, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFechaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFechaMouseReleased
        System.out.println(jFecha.getDate());
    }//GEN-LAST:event_jFechaMouseReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.tbl();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMVActionPerformed
        String idString = tblVenGen.getValueAt(tblVenGen.getSelectedRow(), 0).toString();
        int idVe = Integer.parseInt(idString);
        MostrarVent Mosv = new MostrarVent(idVe);
        Mosv.setVisible(true);
        
    }//GEN-LAST:event_btnMVActionPerformed

    private void btnEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEVActionPerformed
        this.EliminarVent();
        this.tbl();
    }//GEN-LAST:event_btnEVActionPerformed

    public void tbl(){
        sqlGestion sqlges = new sqlGestion();
        Gestion ges = new Gestion();
        
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column==1){
                    return true;
                }else{
                    return false;
                }
            } 
        };
        tblVenGen.getTableHeader().setReorderingAllowed(false) ;
        TEstVen = this.tblVenGen;
        TEstVen.setModel(dtm);
        
        dtm.setColumnIdentifiers(new Object[]{"ID","Total","Estado","Metodo de Pago","Cliente"});
        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        String date = dcn.format(jFecha.getDate() );
        ges.setFecha(date.toString());
        rs = sqlges.SelectVent(ges);
        try {
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString("v.idVent"),rs.getDouble("v.total"),rs.getString("ve.Estado"),rs.getString("m.Metodo"),rs.getString("c.Nombre")+" "+rs.getString("c.Apellidos")});
            }
            this.sumaTot();
            int filas = dtm.getRowCount();
            lblTotVent.setText(String.valueOf(filas)); 
        } catch (Exception e) {
            System.err.println(e);
        }    
        
        Ventas ven = new Ventas();
        
        tblVenGen.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent Mouse_evt){
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if(Mouse_evt.getClickCount() == 1){
                   idV = Integer.parseInt(tblVenGen.getValueAt(tblVenGen.getSelectedRow(), 0).toString());
                    
                }
            }
        });

    }
    
    public double sumaTot(){
        int contar = tblVenGen.getRowCount();
        double Total = 0;
        for(int i = 0; i < contar ; i++){
            Total = Total + Double.parseDouble(tblVenGen.getValueAt(i, 1).toString());
        }
        String tot = Double.toString(Total);
        this.lblDinTot.setText(tot);
        return Total;
    }
    
    public void EliminarVent(){
        sqlVentas sqlVen = new sqlVentas();
        Ventas ven = new Ventas();
        
        ven.setIdVent(idV);
        if(sqlVen.DeleteVentas(ven)){
            JOptionPane.showMessageDialog(null, "Venta eliminada");
        }else{
            JOptionPane.showMessageDialog(null, "Error al eliminar");
        } 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnBuscar;
    javax.swing.JButton btnEV;
    javax.swing.JButton btnMV;
    com.toedter.calendar.JDateChooser jFecha;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JLabel lblDinTot;
    javax.swing.JLabel lblTotVent;
    javax.swing.JTable tblVenGen;
    // End of variables declaration//GEN-END:variables
}
