/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Clientes;

import Controlador.Clientes;
import Controlador.Ventas;
import Modelo.sqlClientes;
import Modelo.sqlInventario;
import Modelo.sqlVentas;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Puga
 */
public class mostrarClientes extends javax.swing.JPanel {

    JTable TClien;
    ResultSet rs;
    int idC;
    public mostrarClientes() {
        initComponents();
        this.tbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClien = new javax.swing.JTable();

        tblClien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblClien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1276, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void tbl(){
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column==1){
                    return true;
                }else{
                    return false;
                }
            } 
        };
        tblClien.getTableHeader().setReorderingAllowed(false) ;
        TClien = this.tblClien;
        TClien.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"ID","Nombre","Apellido","Edad","Telefono", "Email"});
        sqlClientes sqlClien = new sqlClientes();
        rs = sqlClien.SelectClien();
        try {
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getInt("idCliente"),rs.getString("Nombre"),rs.getString("Apellidos"),rs.getInt("Edad"),rs.getString("Telefono"),rs.getString("Email")});
            }
        } catch (Exception e) {
            System.err.println(e);
        }
        
        tblClien.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent Mouse_evt){
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if(Mouse_evt.getClickCount() == 1){
                   idC = Integer.parseInt(tblClien.getValueAt(tblClien.getSelectedRow(), 0).toString());
                    
                }
            }
        });
    }
    
    
    public void EliminarVent(){
        sqlClientes sqClientes = new sqlClientes();
        Clientes cli = new Clientes();
        
        cli.setIdCliente(idC);
        if(sqClientes.DeleteClien(cli)){
            JOptionPane.showMessageDialog(null, "Cliente Eliminado");
        }else{
            JOptionPane.showMessageDialog(null, "Error al eliminar");
        } 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClien;
    // End of variables declaration//GEN-END:variables
}
