/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Clientes;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author issacpuga
 */
public class panelClientes extends javax.swing.JPanel {

    /**
     * Creates new form panelClientes
     */
    public panelClientes() {
        initComponents();
        this.setBackground(Color.WHITE);
        
        
        mostrarClientes mostClien = new mostrarClientes();
        mostClien.setSize(1288, 570);
        mostClien.setLocation(0, 0);
        pClien.removeAll();
        pClien.add(mostClien, BorderLayout.CENTER);
        pClien.revalidate();
        pClien.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pClien = new javax.swing.JPanel();
        btnMostr = new javax.swing.JButton();
        btnAgg = new javax.swing.JButton();

        javax.swing.GroupLayout pClienLayout = new javax.swing.GroupLayout(pClien);
        pClien.setLayout(pClienLayout);
        pClienLayout.setHorizontalGroup(
            pClienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pClienLayout.setVerticalGroup(
            pClienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        btnMostr.setText("Clientes");
        btnMostr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrActionPerformed(evt);
            }
        });

        btnAgg.setText("Agregar");
        btnAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pClien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMostr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgg)
                .addContainerGap(1132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostr)
                    .addComponent(btnAgg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pClien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrActionPerformed
        mostrarClientes mostClien = new mostrarClientes();
        mostClien.setSize(1288, 570);
        mostClien.setLocation(0, 0);
        pClien.removeAll();
        pClien.add(mostClien, BorderLayout.CENTER);
        pClien.revalidate();
        pClien.repaint();
    }//GEN-LAST:event_btnMostrActionPerformed

    private void btnAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggActionPerformed
        AggClientes aggClien = new AggClientes();
        aggClien.setSize(1288, 570);
        aggClien.setLocation(0, 0);
        pClien.removeAll();
        pClien.add(aggClien , BorderLayout.CENTER);
        pClien.revalidate();
        pClien.repaint();
    }//GEN-LAST:event_btnAggActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnAgg;
    javax.swing.JButton btnMostr;
    javax.swing.JPanel pClien;
    // End of variables declaration//GEN-END:variables
}
